my_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: data-db                 # PostgreSQL en docker-compose
      user: myuser                  # contenedor de PostgreSQL
      password: mypassword          # contenedor de PostgreSQL
      dbname: amn_datawarehouse     # contenedor de PostgreSQL
      port: 5432                    
      schema: public                
      threads: 1
      keepalives_idle: 300